#+ defaults:
#+   - endpoint: https://nanopub.sdsc.edu/repo/full

select * where {
  optional { <x:> <x:> ?__endpoint_iri } .
  bind(coalesce(?__endpoint_iri, <https://nanopub.sdsc.edu/repo/full>) as ?ep)
  ?a ?b ?c .
} limit 10
