#+ defaults:
#+   - endpoint: https://nanopub.sdsc.edu/repo/full

select * where {
  optional { <x:> <x:> ?__endpoint_iri } .
  bind(coalesce(?__endpoint_iri, <https://nanopub.sdsc.edu/repo/full>) as ?endpoint)
  bind(iri(replace(str(?endpoint), "[a-zA-Z0-9]+/[a-zA-Z0-9]+$", "")) as ?service)
  ?a ?b ?c .
} limit 10
